const IMAGENET_CLASSES = {
    0: 'tench, Tinca tinca',
    1: 'goldfish, Carassius auratus',
    2: 'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias',
    3: 'tiger shark, Galeocerdo cuvieri',
    4: 'hammerhead, hammerhead shark',
    5: 'electric ray, crampfish, numbfish, torpedo',
    6: 'stingray',
    7: 'cock',
    8: 'hen',
    9: 'ostrich, Struthio camelus',
    10: 'brambling, Fringilla montifringilla',
    11: 'goldfinch, Carduelis carduelis',
    12: 'house finch, linnet, Carpodacus mexicanus',
    13: 'junco, snowbird',
    14: 'indigo bunting, indigo finch, indigo bird, Passerina cyanea',
    15: 'robin, American robin, Turdus migratorius',
    16: 'bulbul',
    17: 'jay',
    18: 'magpie',
    19: 'chickadee',
    20: 'water ouzel, dipper',
    21: 'kite',
    22: 'bald eagle, American eagle, Haliaeetus leucocephalus',
    23: 'vulture',
    24: 'great grey owl, great gray owl, Strix nebulosa',
    25: 'European fire salamander, Salamandra salamandra',
    26: 'common newt, Triturus vulgaris',
    27: 'eft',
    28: 'spotted salamander, Ambystoma maculatum',
    29: 'axolotl, mud puppy, Ambystoma mexicanum',
    30: 'bullfrog, Rana catesbeiana',
    31: 'tree frog, tree-frog',
    32: 'tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui',
    33: 'loggerhead, loggerhead turtle, Caretta caretta',
    34: 'leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea',
    35: 'mud turtle',
    36: 'terrapin',
    37: 'box turtle, box tortoise',
    38: 'banded gecko',
    39: 'common iguana, iguana, Iguana iguana',
    40: 'American chameleon, anole, Anolis carolinensis',
    41: 'whiptail, whiptail lizard',
    42: 'agama',
    43: 'frilled lizard, Chlamydosaurus kingi',
    44: 'alligator lizard',
    45: 'Gila monster, Heloderma suspectum',
    46: 'green lizard, Lacerta viridis',
    47: 'African chameleon, Chamaeleo chamaeleon',
    48: 'Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis',
    49: 'African crocodile, Nile crocodile, Crocodylus niloticus',
    50: 'American alligator, Alligator mississipiensis',
    51: 'triceratops',
    52: 'thunder snake, worm snake, Carphophis amoenus',
    53: 'ringneck snake, ring-necked snake, ring snake',
    54: 'hognose snake, puff adder, sand viper',
    55: 'green snake, grass snake',
    56: 'king snake, kingsnake',
    57: 'garter snake, grass snake',
    58: 'water snake',
    59: 'vine snake',
    60: 'night snake, Hypsiglena torquata',
    61: 'boa constrictor, Constrictor constrictor',
    62: 'rock python, rock snake, Python sebae',
    63: 'Indian cobra, Naja naja',
    64: 'green mamba',
    65: 'sea snake',
    66: 'horned viper, cerastes, sand viper, horned asp, Cerastes cornutus',
    67: 'diamondback, diamondback rattlesnake, Crotalus adamanteus',
    68: 'sidewinder, horned rattlesnake, Crotalus cerastes',
    69: 'trilobite',
    70: 'harvestman, daddy longlegs, Phalangium opilio',
    71: 'scorpion',
    72: 'black and gold garden spider, Argiope aurantia',
    73: 'barn spider, Araneus cavaticus',
    74: 'garden spider, Aranea diademata',
    75: 'black widow, Latrodectus mactans',
    76: 'tarantula',
    77: 'wolf spider, hunting spider',
    78: 'tick',
    79: 'centipede',
    80: 'black grouse',
    81: 'ptarmigan',
    82: 'ruffed grouse, partridge, Bonasa umbellus',
    83: 'prairie chicken, prairie grouse, prairie fowl',
    84: 'peacock',
    85: 'quail',
    86: 'partridge',
    87: 'African grey, African gray, Psittacus erithacus',
    88: 'macaw',
    89: 'sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita',
    90: 'lorikeet',
    91: 'coucal',
    92: 'bee eater',
    93: 'hornbill',
    94: 'hummingbird',
    95: 'jacamar',
    96: 'toucan',
    97: 'drake',
    98: 'red-breasted merganser, Mergus serrator',
    99: 'goose',
    100: 'black swan, Cygnus atratus',
    101: 'tusker',
    102: 'echidna, spiny anteater, anteater',
    103: 'platypus, duckbill, duckbilled platypus, duck-billed platypus, Ornithorhynchus anatinus',
    104: 'wallaby, brush kangaroo',
    105: 'koala, koala bear, kangaroo bear, native bear, Phascolarctos cinereus',
    106: 'wombat',
    107: 'jellyfish',
    108: 'sea anemone, anemone',
    109: 'brain coral',
    110: 'flatworm, platyhelminth',
    111: 'nematode, nematode worm, roundworm',
    112: 'conch',
    113: 'snail',
    114: 'slug',
    115: 'sea slug, nudibranch',
    116: 'chiton, coat-of-mail shell, sea cradle, polyplacophore',
    117: 'chambered nautilus, pearly nautilus, nautilus',
    118: 'Dungeness crab, Cancer magister',
    119: 'rock crab, Cancer irroratus',
    120: 'fiddler crab',
    121: 'king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica',
    122: 'American lobster, Northern lobster, Maine lobster, Homarus americanus',
    123: 'spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish',
    124: 'crayfish, crawfish, crawdad, crawdaddy',
    125: 'hermit crab',
    126: 'isopod',
    127: 'white stork, Ciconia ciconia',
    128: 'black stork, Ciconia nigra',
    129: 'spoonbill',
    130: 'flamingo',
    131: 'little blue heron, Egretta caerulea',
    132: 'American egret, great white heron, Egretta albus',
    133: 'bittern',
    134: 'crane',
    135: 'limpkin, Aramus pictus',
    136: 'European gallinule, Porphyrio porphyrio',
    137: 'American coot, marsh hen, mud hen, water hen, Fulica americana',
    138: 'bustard',
    139: 'ruddy turnstone, Arenaria interpres',
    140: 'red-backed sandpiper, dunlin, Erolia alpina',
    141: 'redshank, Tringa totanus',
    142: 'dowitcher',
    143: 'oystercatcher, oyster catcher',
    144: 'pelican',
    145: 'king penguin, Aptenodytes patagonica',
    146: 'albatross, mollymawk',
    147: 'grey whale, gray whale, devilfish, Eschrichtius gibbosus, Eschrichtius robustus',
    148: 'killer whale, killer, orca, grampus, sea wolf, Orcinus orca',
    149: 'dugong, Dugong dugon',
    150: 'sea lion',
    151: 'Chihuahua',
    152: 'Japanese spaniel',
    153: 'Maltese dog, Maltese terrier, Maltese',
    154: 'Pekinese, Pekingese, Peke',
    155: 'Shih-Tzu',
    156: 'Blenheim spaniel',
    157: 'papillon',
    158: 'toy terrier',
    159: 'Rhodesian ridgeback',
    160: 'Afghan hound, Afghan',
    161: 'basset, basset hound',
    162: 'beagle',
    163: 'bloodhound, sleuthhound',
    164: 'bluetick',
    165: 'black-and-tan coonhound',
    166: 'Walker hound, Walker foxhound',
    167: 'English foxhound',
    168: 'redbone',
    169: 'borzoi, Russian wolfhound',
    170: 'Irish wolfhound',
    171: 'Italian greyhound',
    172: 'whippet',
    173: 'Ibizan hound, Ibizan Podenco',
    174: 'Norwegian elkhound, elkhound',
    175: 'otterhound, otter hound',
    176: 'Saluki, gazelle hound',
    177: 'Scottish deerhound, deerhound',
    178: 'Weimaraner',
    179: 'Staffordshire bullterrier, Staffordshire bull terrier',
    180: 'American Staffordshire terrier, Staffordshire terrier, American pit bull terrier, pit bull terrier',
    181: 'Bedlington terrier',
    182: 'Border terrier',
    183: 'Kerry blue terrier',
    184: 'Irish terrier',
    185: 'Norfolk terrier',
    186: 'Norwich terrier',
    187: 'Yorkshire terrier',
    188: 'wire-haired fox terrier',
    189: 'Lakeland terrier',
    190: 'Sealyham terrier, Sealyham',
    191: 'Airedale, Airedale terrier',
    192: 'cairn, cairn terrier',
    193: 'Australian terrier',
    194: 'Dandie Dinmont, Dandie Dinmont terrier',
    195: 'Boston bull, Boston terrier',
    196: 'miniature schnauzer',
    197: 'giant schnauzer',
    198: 'standard schnauzer',
    199: 'Scotch terrier, Scottish terrier, Scottie',
    200: 'Tibetan terrier, chrysanthemum dog',
    201: 'silky terrier, Sydney silky',
    202: 'soft-coated wheaten terrier',
    203: 'West Highland white terrier',
    204: 'Lhasa, Lhasa apso',
    205: 'flat-coated retriever',
    206: 'curly-coated retriever',
    207: 'golden retriever',
    208: 'Labrador retriever',
    209: 'Chesapeake Bay retriever',
    210: 'German short-haired pointer',
    211: 'vizsla, Hungarian pointer',
    212: 'English setter',
    213: 'Irish setter, red setter',
    214: 'Gordon setter',
    215: 'Brittany spaniel',
    216: 'clumber, clumber spaniel',
    217: 'English springer, English springer spaniel',
    218: 'Welsh springer spaniel',
    219: 'cocker spaniel, English cocker spaniel, cocker',
    220: 'Sussex spaniel',
    221: 'Irish water spaniel',
    222: 'kuvasz',
    223: 'schipperke',
    224: 'groenendael',
    225: 'malinois',
    226: 'briard',
    227: 'kelpie',
    228: 'komondor',
    229: 'Old English sheepdog, bobtail',
    230: 'Shetland sheepdog, Shetland sheep dog, Shetland',
    231: 'collie',
    232: 'Border collie',
    233: 'Bouvier des Flandres, Bouviers des Flandres',
    234: 'Rottweiler',
    235: 'German shepherd, German shepherd dog, German police dog, alsatian',
    236: 'Doberman, Doberman pinscher',
    237: 'miniature pinscher',
    238: 'Greater Swiss Mountain dog',
    239: 'Bernese mountain dog',
    240: 'Appenzeller',
    241: 'EntleBucher',
    242: 'boxer',
    243: 'bull mastiff',
    244: 'Tibetan mastiff',
    245: 'French bulldog',
    246: 'Great Dane',
    247: 'Saint Bernard, St Bernard',
    248: 'Eskimo dog, husky',
    249: 'malamute, malemute, Alaskan malamute',
    250: 'Siberian husky',
    251: 'dalmatian, coach dog, carriage dog',
    252: 'affenpinscher, monkey pinscher, monkey dog',
    253: 'basenji',
    254: 'pug, pug-dog',
    255: 'Leonberg',
    256: 'Newfoundland, Newfoundland dog',
    257: 'Great Pyrenees',
    258: 'Samoyed, Samoyede',
    259: 'Pomeranian',
    260: 'chow, chow chow',
    261: 'keeshond',
    262: 'Brabancon griffon',
    263: 'Pembroke, Pembroke Welsh corgi',
    264: 'Cardigan, Cardigan Welsh corgi',
    265: 'toy poodle',
    266: 'miniature poodle',
    267: 'standard poodle',
    268: 'Mexican hairless',
    269: 'timber wolf, grey wolf, gray wolf, Canis lupus',
    270: 'white wolf, Arctic wolf, Canis lupus tundrarum',
    271: 'red wolf, maned wolf, Canis rufus, Canis niger',
    272: 'coyote, prairie wolf, brush wolf, Canis latrans',
    273: 'dingo, warrigal, warragal, Canis dingo',
    274: 'dhole, Cuon alpinus',
    275: 'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus',
    276: 'hyena, hyaena',
    277: 'red fox, Vulpes vulpes',
    278: 'kit fox, Vulpes macrotis',
    279: 'Arctic fox, white fox, Alopex lagopus',
    280: 'grey fox, gray fox, Urocyon cinereoargenteus',
    281: 'tabby, tabby cat',
    282: 'tiger cat',
    283: 'Persian cat',
    284: 'Siamese cat, Siamese',
    285: 'Egyptian cat',
    286: 'cougar, puma, catamount, mountain lion, painter, panther, Felis concolor',
    287: 'lynx, catamount',
    288: 'leopard, Panthera pardus',
    289: 'snow leopard, ounce, Panthera uncia',
    290: 'jaguar, panther, Panthera onca, Felis onca',
    291: 'lion, king of beasts, Panthera leo',
    292: 'tiger, Panthera tigris',
    293: 'cheetah, chetah, Acinonyx jubatus',
    294: 'brown bear, bruin, Ursus arctos',
    295: 'American black bear, black bear, Ursus americanus, Euarctos americanus',
    296: 'ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus',
    297: 'sloth bear, Melursus ursinus, Ursus ursinus',
    298: 'mongoose',
    299: 'meerkat, mierkat',
    300: 'tiger beetle',
    301: 'ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle',
    302: 'ground beetle, carabid beetle',
    303: 'long-horned beetle, longicorn, longicorn beetle',
    304: 'leaf beetle, chrysomelid',
    305: 'dung beetle',
    306: 'rhinoceros beetle',
    307: 'weevil',
    308: 'fly',
    309: 'bee',
    310: 'ant, emmet, pismire',
    311: 'grasshopper, hopper',
    312: 'cricket',
    313: 'walking stick, walkingstick, stick insect',
    314: 'cockroach, roach',
    315: 'mantis, mantid',
    316: 'cicada, cicala',
    317: 'leafhopper',
    318: 'lacewing, lacewing fly',
    319: 'dragonfly, darning needle, devil\'s darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk, skeeter hawk',
    320: 'damselfly',
    321: 'admiral',
    322: 'ringlet, ringlet butterfly',
    323: 'monarch, monarch butterfly, milkweed butterfly, Danaus plexippus',
    324: 'cabbage butterfly',
    325: 'sulphur butterfly, sulfur butterfly',
    326: 'lycaenid, lycaenid butterfly',
    327: 'starfish, sea star',
    328: 'sea urchin',
    329: 'sea cucumber, holothurian',
    330: 'wood rabbit, cottontail, cottontail rabbit',
    331: 'hare',
    332: 'Angora, Angora rabbit',
    333: 'hamster',
    334: 'porcupine, hedgehog',
    335: 'fox squirrel, eastern fox squirrel, Sciurus niger',
    336: 'marmot',
    337: 'beaver',
    338: 'guinea pig, Cavia cobaya',
    339: 'sorrel',
    340: 'zebra',
    341: 'hog, pig, grunter, squealer, Sus scrofa',
    342: 'wild boar, boar, Sus scrofa',
    343: 'warthog',
    344: 'hippopotamus, hippo, river horse, Hippopotamus amphibius',
    345: 'ox',
    346: 'water buffalo, water ox, Asiatic buffalo, Bubalus bubalis',
    347: 'bison',
    348: 'ram, tup',
    349: 'bighorn, bighorn sheep, cimarron, Rocky Mountain bighorn, Rocky Mountain sheep, Ovis canadensis',
    350: 'ibex, Capra ibex',
    351: 'hartebeest',
    352: 'impala, Aepyceros melampus',
    353: 'gazelle',
    354: 'Arabian camel, dromedary, Camelus dromedarius',
    355: 'llama',
    356: 'weasel',
    357: 'mink',
    358: 'polecat, fitch, foulmart, foumart, Mustela putorius',
    359: 'black-footed ferret, ferret, Mustela nigripes',
    360: 'otter',
    361: 'skunk, polecat, wood pussy',
    362: 'badger',
    363: 'armadillo',
    364: 'three-toed sloth, ai, Bradypus tridactylus',
    365: 'orangutan, orang, orangutang, Pongo pygmaeus',
    366: 'gorilla, Gorilla gorilla',
    367: 'chimpanzee, chimp, Pan troglodytes',
    368: 'gibbon, Hylobates lar',
    369: 'siamang, Hylobates syndactylus, Symphalangus syndactylus',
    370: 'guenon, guenon monkey',
    371: 'patas, hussar monkey, Erythrocebus patas',
    372: 'baboon',
    373: 'macaque',
    374: 'langur',
    375: 'colobus, colobus monkey',
    376: 'proboscis monkey, Nasalis larvatus',
    377: 'marmoset',
    378: 'capuchin, ringtail, Cebus capucinus',
    379: 'howler monkey, howler',
    380: 'titi, titi monkey',
    381: 'spider monkey, Ateles geoffroyi',
    382: 'squirrel monkey, Saimiri sciureus',
    383: 'Madagascar cat, ring-tailed lemur, Lemur catta',
    384: 'indri, indris, Indri indri, Indri brevicaudatus',
    385: 'Indian elephant, Elephas maximus',
    386: 'African elephant, Loxodonta africana',
    387: 'lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens',
    388: 'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca',
    389: 'barracouta, snoek',
    390: 'eel',
    391: 'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch',
    392: 'rock beauty, Holocanthus tricolor',
    393: 'anemone fish',
    394: 'sturgeon',
    395: 'gar, garfish, garpike, billfish, Lepisosteus osseus',
    396: 'lionfish',
    397: 'puffer, pufferfish, blowfish, globefish',
    398: 'abacus',
    399: 'abaya',
    400: 'academic gown, academic robe, judge\'s robe',
    401: 'accordion, piano accordion, squeeze box',
    402: 'acoustic guitar',
    403: 'aircraft carrier, carrier, flattop, attack aircraft carrier',
    404: 'airliner',
    405: 'airship, dirigible',
    406: 'altar',
    407: 'ambulance',
    408: 'amphibian, amphibious vehicle',
    409: 'analog clock',
    410: 'apiary, bee house',
    411: 'apron',
    412: 'ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin',
    413: 'assault rifle, assault gun',
    414: 'attractor',
    415: 'ax, axe',
    416: 'bakery, bakeshop, bakehouse',
    417: 'balance beam, beam',
    418: 'balloon',
    419: 'ballpoint, ballpoint pen, ballpen, Biro',
    420: 'Band Aid',
    421: 'banjo',
    422: 'bannister, banister, balustrade, balusters, handrail',
    423: 'barbell',
    424: 'barber chair',
    425: 'barbershop',
    426: 'barn',
    427: 'barometer',
    428: 'barrel, cask',
    429: 'barrow, garden cart, lawn cart, wheelbarrow',
    430: 'baseball',
    431: 'basketball',
    432: 'bassinet',
    433: 'bassoon',
    434: 'bathing cap, swimming cap',
    435: 'bath towel',
    436: 'bathtub, bathing tub, bath, tub',
    437: 'beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon',
    438: 'beacon, lighthouse, beacon light, pharos',
    439: 'beaker',
    440: 'bearskin, busby, shako',
    441: 'beer bottle',
    442: 'beer glass',
    443: 'bell cote, bell cot',
    444: 'bib',
    445: 'bicycle-built-for-two, tandem bicycle, tandem',
    446: 'bikini, two-piece',
    447: 'binder, ring-binder',
    448: 'binoculars, field glasses, opera glasses',
    449: 'birdhouse',
    450: 'boathouse',
    451: 'bobsled, bobsleigh, bob',
    452: 'bolo tie, bolo, bola tie, bola',
    453: 'bonnet, poke bonnet',
    454: 'bookcase',
    455: 'bookshop, bookstore, bookstall',
    456: 'bottlecap',
    457: 'bow',
    458: 'bow tie, bow-tie, bowtie',
    459: 'brass, memorial tablet, plaque',
    460: 'brassiere, bra, bandeau',
    461: 'breakwater, groin, groyne, mole, bulwark, seawall, jetty',
    462: 'breastplate, aegis, egis',
    463: 'broom',
    464: 'bucket, pail',
    465: 'buckle',
    466: 'bulletproof vest',
    467: 'bullet train, bullet',
    468: 'butcher shop, meat market',
    469: 'cab, hack, taxi, taxicab',
    470: 'caldron, cauldron',
    471: 'candle, taper, wax light',
    472: 'cannon',
    473: 'canoe',
    474: 'can opener, tin opener',
    475: 'cardigan',
    476: 'car mirror',
    477: 'carousel, carrousel, merry-go-round, roundabout, whirligig',
    478: 'carpenter\'s kit, tool kit',
    479: 'carton',
    480: 'car wheel',
    481: 'cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM',
    482: 'cassette',
    483: 'cassette player',
    484: 'castle',
    485: 'catamaran',
    486: 'CD player',
    487: 'cello, violoncello',
    488: 'cellular telephone, cellular phone, cellphone, cell, mobile phone',
    489: 'chain',
    490: 'chainlink fence',
    491: 'chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour',
    492: 'chain saw, chainsaw',
    493: 'chest',
    494: 'chiffonier, commode',
    495: 'chime, bell, gong',
    496: 'china cabinet, china closet',
    497: 'Christmas stocking',
    498: 'church, church building',
    499: 'cinema, movie theater, movie theatre, movie house, picture palace',
    500: 'cleaver, meat cleaver, chopper',
    501: 'cliff dwelling',
    502: 'cloak',
    503: 'clog, geta, patten, sabot',
    504: 'cocktail shaker',
    505: 'coffee mug',
    506: 'coffeepot',
    507: 'coil, spiral, volute, whorl, helix',
    508: 'combination lock',
    509: 'computer keyboard, keypad',
    510: 'confectionery, confectionary, candy store',
    511: 'container ship, containership, container vessel',
    512: 'convertible',
    513: 'corkscrew, bottle screw',
    514: 'cornet, horn, trumpet, trump',
    515: 'cowboy boot',
    516: 'cowboy hat, ten-gallon hat',
    517: 'cradle',
    518: 'crane',
    519: 'crash helmet',
    520: 'crate',
    521: 'crib, cot',
    522: 'Crock Pot',
    523: 'croquet ball',
    524: 'crutch',
    525: 'cuirass',
    526: 'dam, dike, dyke',
    527: 'desk',
    528: 'desktop computer',
    529: 'dial telephone, dial phone',
    530: 'diaper, nappy, napkin',
    531: 'digital clock',
    532: 'digital watch',
    533: 'dining table, board',
    534: 'dishrag, dishcloth',
    535: 'dishwasher, dish washer, dishwashing machine',
    536: 'disk brake, disc brake',
    537: 'dock, dockage, docking facility',
    538: 'dogsled, dog sled, dog sleigh',
    539: 'dome',
    540: 'doormat, welcome mat',
    541: 'drilling platform, offshore rig',
    542: 'drum, membranophone, tympan',
    543: 'drumstick',
    544: 'dumbbell',
    545: 'Dutch oven',
    546: 'electric fan, blower',
    547: 'electric guitar',
    548: 'electric locomotive',
    549: 'entertainment center',
    550: 'envelope',
    551: 'espresso maker',
    552: 'face powder',
    553: 'feather boa, boa',
    554: 'file, file cabinet, filing cabinet',
    555: 'fireboat',
    556: 'fire engine, fire truck',
    557: 'fire screen, fireguard',
    558: 'flagpole, flagstaff',
    559: 'flute, transverse flute',
    560: 'folding chair',
    561: 'football helmet',
    562: 'forklift',
    563: 'fountain',
    564: 'fountain pen',
    565: 'four-poster',
    566: 'freight car',
    567: 'French horn, horn',
    568: 'frying pan, frypan, skillet',
    569: 'fur coat',
    570: 'garbage truck, dustcart',
    571: 'gasmask, respirator, gas helmet',
    572: 'gas pump, gasoline pump, petrol pump, island dispenser',
    573: 'goblet',
    574: 'go-kart',
    575: 'golf ball',
    576: 'golfcart, golf cart',
    577: 'gondola',
    578: 'gong, tam-tam',
    579: 'gown',
    580: 'grand piano, grand',
    581: 'greenhouse, nursery, glasshouse',
    582: 'grille, radiator grille',
    583: 'grocery store, grocery, food market, market',
    584: 'guillotine',
    585: 'hair slide',
    586: 'hair spray',
    587: 'half track',
    588: 'hammer',
    589: 'hamper',
    590: 'hand blower, blow dryer, blow drier, hair dryer, hair drier',
    591: 'hand-held computer, hand-held microcomputer',
    592: 'handkerchief, hankie, hanky, hankey',
    593: 'hard disc, hard disk, fixed disk',
    594: 'harmonica, mouth organ, harp, mouth harp',
    595: 'harp',
    596: 'harvester, reaper',
    597: 'hatchet',
    598: 'holster',
    599: 'home theater, home theatre',
    600: 'honeycomb',
    601: 'hook, claw',
    602: 'hoopskirt, crinoline',
    603: 'horizontal bar, high bar',
    604: 'horse cart, horse-cart',
    605: 'hourglass',
    606: 'iPod',
    607: 'iron, smoothing iron',
    608: 'jack-o\'-lantern',
    609: 'jean, blue jean, denim',
    610: 'jeep, landrover',
    611: 'jersey, T-shirt, tee shirt',
    612: 'jigsaw puzzle',
    613: 'jinrikisha, ricksha, rickshaw',
    614: 'joystick',
    615: 'kimono',
    616: 'knee pad',
    617: 'knot',
    618: 'lab coat, laboratory coat',
    619: 'ladle',
    620: 'lampshade, lamp shade',
    621: 'laptop, laptop computer',
    622: 'lawn mower, mower',
    623: 'lens cap, lens cover',
    624: 'letter opener, paper knife, paperknife',
    625: 'library',
    626: 'lifeboat',
    627: 'lighter, light, igniter, ignitor',
    628: 'limousine, limo',
    629: 'liner, ocean liner',
    630: 'lipstick, lip rouge',
    631: 'Loafer',
    632: 'lotion',
    633: 'loudspeaker, speaker, speaker unit, loudspeaker system, speaker system',
    634: 'loupe, jeweler\'s loupe',
    635: 'lumbermill, sawmill',
    636: 'magnetic compass',
    637: 'mailbag, postbag',
    638: 'mailbox, letter box',
    639: 'maillot',
    640: 'maillot, tank suit',
    641: 'manhole cover',
    642: 'maraca',
    643: 'marimba, xylophone',
    644: 'mask',
    645: 'matchstick',
    646: 'maypole',
    647: 'maze, labyrinth',
    648: 'measuring cup',
    649: 'medicine chest, medicine cabinet',
    650: 'megalith, megalithic structure',
    651: 'microphone, mike',
    652: 'microwave, microwave oven',
    653: 'military uniform',
    654: 'milk can',
    655: 'minibus',
    656: 'miniskirt, mini',
    657: 'minivan',
    658: 'missile',
    659: 'mitten',
    660: 'mixing bowl',
    661: 'mobile home, manufactured home',
    662: 'Model T',
    663: 'modem',
    664: 'monastery',
    665: 'monitor',
    666: 'moped',
    667: 'mortar',
    668: 'mortarboard',
    669: 'mosque',
    670: 'mosquito net',
    671: 'motor scooter, scooter',
    672: 'mountain bike, all-terrain bike, off-roader',
    673: 'mountain tent',
    674: 'mouse, computer mouse',
    675: 'mousetrap',
    676: 'moving van',
    677: 'muzzle',
    678: 'nail',
    679: 'neck brace',
    680: 'necklace',
    681: 'nipple',
    682: 'notebook, notebook computer',
    683: 'obelisk',
    684: 'oboe, hautboy, hautbois',
    685: 'ocarina, sweet potato',
    686: 'odometer, hodometer, mileometer, milometer',
    687: 'oil filter',
    688: 'organ, pipe organ',
    689: 'oscilloscope, scope, cathode-ray oscilloscope, CRO',
    690: 'overskirt',
    691: 'oxcart',
    692: 'oxygen mask',
    693: 'packet',
    694: 'paddle, boat paddle',
    695: 'paddlewheel, paddle wheel',
    696: 'padlock',
    697: 'paintbrush',
    698: 'pajama, pyjama, pj\'s, jammies',
    699: 'palace',
    700: 'panpipe, pandean pipe, syrinx',
    701: 'paper towel',
    702: 'parachute, chute',
    703: 'parallel bars, bars',
    704: 'park bench',
    705: 'parking meter',
    706: 'passenger car, coach, carriage',
    707: 'patio, terrace',
    708: 'pay-phone, pay-station',
    709: 'pedestal, plinth, footstall',
    710: 'pencil box, pencil case',
    711: 'pencil sharpener',
    712: 'perfume, essence',
    713: 'Petri dish',
    714: 'photocopier',
    715: 'pick, plectrum, plectron',
    716: 'pickelhaube',
    717: 'picket fence, paling',
    718: 'pickup, pickup truck',
    719: 'pier',
    720: 'piggy bank, penny bank',
    721: 'pill bottle',
    722: 'pillow',
    723: 'ping-pong ball',
    724: 'pinwheel',
    725: 'pirate, pirate ship',
    726: 'pitcher, ewer',
    727: 'plane, carpenter\'s plane, woodworking plane',
    728: 'planetarium',
    729: 'plastic bag',
    730: 'plate rack',
    731: 'plow, plough',
    732: 'plunger, plumber\'s helper',
    733: 'Polaroid camera, Polaroid Land camera',
    734: 'pole',
    735: 'police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria',
    736: 'poncho',
    737: 'pool table, billiard table, snooker table',
    738: 'pop bottle, soda bottle',
    739: 'pot, flowerpot',
    740: 'potter\'s wheel',
    741: 'power drill',
    742: 'prayer rug, prayer mat',
    743: 'printer',
    744: 'prison, prison house',
    745: 'projectile, missile',
    746: 'projector',
    747: 'puck, hockey puck',
    748: 'punching bag, punch bag, punching ball, punchball',
    749: 'purse',
    750: 'quill, quill pen',
    751: 'quilt, comforter, comfort, puff',
    752: 'racer, race car, racing car',
    753: 'racket, racquet',
    754: 'radiator',
    755: 'radio, wireless',
    756: 'radio telescope, radio reflector',
    757: 'rain barrel',
    758: 'recreational vehicle, RV, R.V.',
    759: 'reel',
    760: 'reflex camera',
    761: 'refrigerator, icebox',
    762: 'remote control, remote',
    763: 'restaurant, eating house, eating place, eatery',
    764: 'revolver, six-gun, six-shooter',
    765: 'rifle',
    766: 'rocking chair, rocker',
    767: 'rotisserie',
    768: 'rubber eraser, rubber, pencil eraser',
    769: 'rugby ball',
    770: 'rule, ruler',
    771: 'running shoe',
    772: 'safe',
    773: 'safety pin',
    774: 'saltshaker, salt shaker',
    775: 'sandal',
    776: 'sarong',
    777: 'sax, saxophone',
    778: 'scabbard',
    779: 'scale, weighing machine',
    780: 'school bus',
    781: 'schooner',
    782: 'scoreboard',
    783: 'screen, CRT screen',
    784: 'screw',
    785: 'screwdriver',
    786: 'seat belt, seatbelt',
    787: 'sewing machine',
    788: 'shield, buckler',
    789: 'shoe shop, shoe-shop, shoe store',
    790: 'shoji',
    791: 'shopping basket',
    792: 'shopping cart',
    793: 'shovel',
    794: 'shower cap',
    795: 'shower curtain',
    796: 'ski',
    797: 'ski mask',
    798: 'sleeping bag',
    799: 'slide rule, slipstick',
    800: 'sliding door',
    801: 'slot, one-armed bandit',
    802: 'snorkel',
    803: 'snowmobile',
    804: 'snowplow, snowplough',
    805: 'soap dispenser',
    806: 'soccer ball',
    807: 'sock',
    808: 'solar dish, solar collector, solar furnace',
    809: 'sombrero',
    810: 'soup bowl',
    811: 'space bar',
    812: 'space heater',
    813: 'space shuttle',
    814: 'spatula',
    815: 'speedboat',
    816: 'spider web, spider\'s web',
    817: 'spindle',
    818: 'sports car, sport car',
    819: 'spotlight, spot',
    820: 'stage',
    821: 'steam locomotive',
    822: 'steel arch bridge',
    823: 'steel drum',
    824: 'stethoscope',
    825: 'stole',
    826: 'stone wall',
    827: 'stopwatch, stop watch',
    828: 'stove',
    829: 'strainer',
    830: 'streetcar, tram, tramcar, trolley, trolley car',
    831: 'stretcher',
    832: 'studio couch, day bed',
    833: 'stupa, tope',
    834: 'submarine, pigboat, sub, U-boat',
    835: 'suit, suit of clothes',
    836: 'sundial',
    837: 'sunglass',
    838: 'sunglasses, dark glasses, shades',
    839: 'sunscreen, sunblock, sun blocker',
    840: 'suspension bridge',
    841: 'swab, swob, mop',
    842: 'sweatshirt',
    843: 'swimming trunks, bathing trunks',
    844: 'swing',
    845: 'switch, electric switch, electrical switch',
    846: 'syringe',
    847: 'table lamp',
    848: 'tank, army tank, armored combat vehicle, armoured combat vehicle',
    849: 'tape player',
    850: 'teapot',
    851: 'teddy, teddy bear',
    852: 'television, television system',
    853: 'tennis ball',
    854: 'thatch, thatched roof',
    855: 'theater curtain, theatre curtain',
    856: 'thimble',
    857: 'thresher, thrasher, threshing machine',
    858: 'throne',
    859: 'tile roof',
    860: 'toaster',
    861: 'tobacco shop, tobacconist shop, tobacconist',
    862: 'toilet seat',
    863: 'torch',
    864: 'totem pole',
    865: 'tow truck, tow car, wrecker',
    866: 'toyshop',
    867: 'tractor',
    868: 'trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi',
    869: 'tray',
    870: 'trench coat',
    871: 'tricycle, trike, velocipede',
    872: 'trimaran',
    873: 'tripod',
    874: 'triumphal arch',
    875: 'trolleybus, trolley coach, trackless trolley',
    876: 'trombone',
    877: 'tub, vat',
    878: 'turnstile',
    879: 'typewriter keyboard',
    880: 'umbrella',
    881: 'unicycle, monocycle',
    882: 'upright, upright piano',
    883: 'vacuum, vacuum cleaner',
    884: 'vase',
    885: 'vault',
    886: 'velvet',
    887: 'vending machine',
    888: 'vestment',
    889: 'viaduct',
    890: 'violin, fiddle',
    891: 'volleyball',
    892: 'waffle iron',
    893: 'wall clock',
    894: 'wallet, billfold, notecase, pocketbook',
    895: 'wardrobe, closet, press',
    896: 'warplane, military plane',
    897: 'washbasin, handbasin, washbowl, lavabo, wash-hand basin',
    898: 'washer, automatic washer, washing machine',
    899: 'water bottle',
    900: 'water jug',
    901: 'water tower',
    902: 'whiskey jug',
    903: 'whistle',
    904: 'wig',
    905: 'window screen',
    906: 'window shade',
    907: 'Windsor tie',
    908: 'wine bottle',
    909: 'wing',
    910: 'wok',
    911: 'wooden spoon',
    912: 'wool, woolen, woollen',
    913: 'worm fence, snake fence, snake-rail fence, Virginia fence',
    914: 'wreck',
    915: 'yawl',
    916: 'yurt',
    917: 'web site, website, internet site, site',
    918: 'comic book',
    919: 'crossword puzzle, crossword',
    920: 'street sign',
    921: 'traffic light, traffic signal, stoplight',
    922: 'book jacket, dust cover, dust jacket, dust wrapper',
    923: 'menu',
    924: 'plate',
    925: 'guacamole',
    926: 'consomme',
    927: 'hot pot, hotpot',
    928: 'trifle',
    929: 'ice cream, icecream',
    930: 'ice lolly, lolly, lollipop, popsicle',
    931: 'French loaf',
    932: 'bagel, beigel',
    933: 'pretzel',
    934: 'cheeseburger',
    935: 'hotdog, hot dog, red hot',
    936: 'mashed potato',
    937: 'head cabbage',
    938: 'broccoli',
    939: 'cauliflower',
    940: 'zucchini, courgette',
    941: 'spaghetti squash',
    942: 'acorn squash',
    943: 'butternut squash',
    944: 'cucumber, cuke',
    945: 'artichoke, globe artichoke',
    946: 'bell pepper',
    947: 'cardoon',
    948: 'mushroom',
    949: 'Granny Smith',
    950: 'strawberry',
    951: 'orange',
    952: 'lemon',
    953: 'fig',
    954: 'pineapple, ananas',
    955: 'banana',
    956: 'jackfruit, jak, jack',
    957: 'custard apple',
    958: 'pomegranate',
    959: 'hay',
    960: 'carbonara',
    961: 'chocolate sauce, chocolate syrup',
    962: 'dough',
    963: 'meat loaf, meatloaf',
    964: 'pizza, pizza pie',
    965: 'potpie',
    966: 'burrito',
    967: 'red wine',
    968: 'espresso',
    969: 'cup',
    970: 'eggnog',
    971: 'alp',
    972: 'bubble',
    973: 'cliff, drop, drop-off',
    974: 'coral reef',
    975: 'geyser',
    976: 'lakeside, lakeshore',
    977: 'promontory, headland, head, foreland',
    978: 'sandbar, sand bar',
    979: 'seashore, coast, seacoast, sea-coast',
    980: 'valley, vale',
    981: 'volcano',
    982: 'ballplayer, baseball player',
    983: 'groom, bridegroom',
    984: 'scuba diver',
    985: 'rapeseed',
    986: 'daisy',
    987: 'yellow lady\'s slipper, yellow lady-slipper, Cypripedium calceolus, Cypripedium parviflorum',
    988: 'corn',
    989: 'acorn',
    990: 'hip, rose hip, rosehip',
    991: 'buckeye, horse chestnut, conker',
    992: 'coral fungus',
    993: 'agaric',
    994: 'gyromitra',
    995: 'stinkhorn, carrion fungus',
    996: 'earthstar',
    997: 'hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa',
    998: 'bolete',
    999: 'ear, spike, capitulum'
};
